#!/usr/bin/env bash

input="$HANDYDEV_ROOT/repos/presentation/inputs/3_full"
output="$HANDYDEV_ROOT/repos/presentation/demos/output"

awk_script="$HOME/.bash_history_filter.awk"

awk -f "$awk_script" "$input" > "$output"

if [[ "$THEME" = 'light' ]]; then
  nvim -dMR "$input" "$output" \
    +'set nonumber nolist nocursorline foldtext=foldtext() foldcolumn=0' \
    +'highlight DiffAdd guibg=#FBECEC' \
    +'highlight DiffDelete guibg=#F7F8F9 guifg=#F7F8F9' \
    +'wincmd w' \
    +'set nonumber nolist nocursorline foldtext=foldtext() foldcolumn=0' \
    +'wincmd w' \
    +'nmap n ]czz' \
    +'nmap p [czz' \
    +'1'
else
  nvim -dMR "$input" "$output" \
    +'set nonumber nolist nocursorline foldtext=foldtext() foldcolumn=0' \
    +'highlight DiffAdd guibg=#6A3F41 guifg=#BBBBBB' \
    +'highlight DiffDelete guibg=#29303E guifg=#29303E' \
    +'wincmd w' \
    +'set nonumber nolist nocursorline foldtext=foldtext() foldcolumn=0' \
    +'wincmd w' \
    +'nmap n ]czz' \
    +'nmap p [czz' \
    +'1'
fi
